Products/urls.py
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from . import views


from rest_framework import routers

app_name = 'Products'
urlpatterns = [
    path('', views.MainView.as_view(), name='Main'),
    # path('products/', views.ProductsView.as_view(), name='Products'),
    path('products/<int:pk>/', views.ProductView.as_view(), name='Product'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='Category'),
    # path('category/', views.CategoriesView.as_view(), name='Categories'),
    path('login/', views.Login.as_view(), name='Login'),
    path('log/', obtain_jwt_token, name='Log'),
    path('out/', views.OutView.as_view(), name='Out'),
    path('test/', views.Test.as_view(), name='test'),
    path('acces/', views.AccesView.as_view(), name='Acces'),
    path('logout/', views.LogoutView.as_view(), name='Logout'),
    path('register/', views.RegisterView.as_view(), name='Register'),
    path('cart/', views.CartView.as_view(), name='Cart'),
    path('password/', views.UserChangPasswordView.as_view(), name='User-password'),
    path('user/', views.UserView.as_view(), name='User'),
    path('producer/<int:pk>/', views.ProducerView.as_view(), name='Producer'),
    path('search/', views.SearchView.as_view(), name='Search'),
    path('register_done/', views.RegisterDone.as_view(), name='register_done'),
    path('reset_password/', views.ResetPasswordView.as_view(), name='reset_password'),
    path('reset_password_sent/', views.ResetPasswordDoneForm.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete', views.ResetPasswordCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<uidb64>/<token>',views.VerificationView.as_view(), name='activate'),
]

sklep/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from Products import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'products', views.ProductsViewSet)
router.register(r'category', views.CategoryViewSet)
router.register(r'producer', views.ProducerViewSet)
router.register(r'cartproducts', views.CartProductsViewSet)
router.register(r'cart', views.CartViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Products.urls')),
    path('rest/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)



class Producer(models.Model):
    def urla(self, filename):
        return os.path.join('images/logo/', filename)

    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to=urla, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Producent'
        verbose_name_plural = 'Producenci'




class Category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategoria'
        verbose_name_plural = 'Kategorie'


class Products(models.Model):

    def urla(self, filename):
        return os.path.join('images/product', filename)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    producer = models.ForeignKey(Producer, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    image = models.ImageField(upload_to=urla,null=True)

    def __str__(self):
        if len(self.title)>50:
            return self.title[:50]+'...'
        return self.title

    class Meta:
        verbose_name = 'Produkt'
        verbose_name_plural = 'Produkty'


class CartProducts(models.Model):
    CartId = models.ForeignKey('cart', on_delete=models.CASCADE, null=True)
    ProductsId = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
    Count = models.IntegerField()

    def SumPrice(self):
        return self.ProductsId.price * self.Count

    def SumPriceAll(self):
        sum=0
        Listprod=CartProducts.objects.filter(CartId= self.CartId)
        for i in Listprod:
            sum += i.Count * i.ProductsId.price
        return sum


class Cart(models.Model):
    UserId = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.pk)

Products/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CartProducts, Products,Cart, User
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import forms
from django.contrib import messages


class CreateUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'username', 'password1', 'password2']

    def save(self, commit=True ):
        instance = super(CreateUserForm, self).save(commit=False)
        instance.is_active = False
        instance.save()


class EditProfilForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['first_name', 'last_name']




class CartProductForm(forms.ModelForm):
    product = forms.IntegerField()
    cart = forms.IntegerField()

    class Meta:
        model = CartProducts
        fields = ['Count']

    def save(self, commit=True ):
        instance = super(CartProductForm, self).save(commit=False)
        instance.ProductsId = Products.objects.get(pk=self.data['product'])
        instance.CartId = Cart.objects.get(pk=self.data['cart'])
        instance.save()


class CartProductChangeCountForm(forms.ModelForm):
    product = forms.IntegerField()

    class Meta:
        model = CartProducts
        fields = ['Count']

    def save(self, commit=True ):
        instance = super(CartProductChangeCountForm, self).save(commit=False)
        c = (self.data['Count'])
        w = int(float(c))

        instance.Count = w
        instance.CartId = CartProducts.objects.get(pk=self.data['product']).CartId

        instance.save()

Products/views.py
import jwt
from django.shortcuts import render, redirect


from .models import Products, Category, Cart, CartProducts, Producer, User
# from django.contrib.auth.models import User

from django.views import generic
from django.views.generic import ListView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.contrib import messages
from .utils import generate_token, send_email
from django.utils.encoding import force_bytes, force_text

from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from django.contrib.sites.shortcuts import get_current_site

from .forms import CreateUserForm, CartProductForm, CartProductChangeCountForm, EditProfilForm
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.exceptions import AuthenticationFailed
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from .serializers import UserSerializer, ProductsSerializer, CategorySerializer, CartSerializer, CartProductsSerializer, ProducerSerializer
from django.core.paginator import Paginator
from .filters import ProductFilter
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMultiAlternatives
from django_filters.views import FilterView
from django.urls import reverse_lazy
# Create your views here.
from django.contrib.messages.views import SuccessMessageMixin
import environ
env = environ.Env(DEBUG=(bool, False))


class ProducerView(generic.DetailView):
    template_name = 'Products/Producer.html'
    context_object_name = 'producer_list'
    model = Producer


class ProductView(generic.DetailView):
    model = Products
    template_name = 'Products/Product.html'


    def post(self, request, pk):
        cart_id_user = Cart.objects.get(UserId=self.request.user.id)
        check_product_in_cart= CartProducts.objects.filter(CartId=cart_id_user, ProductsId=pk)
        form = CartProductForm(request.POST)

        if not check_product_in_cart:
            if form.is_valid():
                form.save()
                messages.info(request, 'dodano produkt do koszyka')
        else:
            messages.info(request, 'produkt juz jest w koszyku')
        return redirect(self.template_name, pk)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            cart_id, bool = Cart.objects.filter(UserId=self.request.user.id).get_or_create(defaults={'UserId': self.request.user})
            context['product_in_cat'] = CartProducts.objects.filter(CartId=cart_id)
            context['cartid'] = cart_id
            context['form'] = CartProductForm()
        return context


class MainView(generic.TemplateView):
    template_name = 'Products/Main.html'


class CategoriesView(generic.ListView):
    template_name = 'Products/Categories.html'


class CategoryView (ListView):
    paginate_by = 3
    template_name = 'Products/Category.html'

    def post(self, request, pk):

        form = CartProductForm(request.POST)
        id_product = request.POST.get('product')
        cart_id_user = Cart.objects.get(UserId=self.request.user.id)
        check_product_in_cart = CartProducts.objects.filter(CartId=cart_id_user, ProductsId=id_product)
        if not check_product_in_cart:
            if form.is_valid():
                form.save()
                messages.info(request, 'dodano produkt')
        else:
            messages.info(request, 'produkt juz w koszyku')
        return super(CategoryView, self).get(request)

    def get_queryset(self):
        queryset = Products.objects.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            cart_id, bool = Cart.objects.filter(UserId=self.request.user.id).get_or_create(
                        defaults={'UserId': self.request.user})
            context['form'] = CartProductForm(initial={'CartId': cart_id, 'ProductsId': self.kwargs.get('pk')})
            context['cart'] = cart_id
            context['cat'] = Category.objects.get(id=self.kwargs.get('pk'))
        return context


class SearchView(FilterView):
    filterset_class = ProductFilter
    template_name = 'Products/Category.html'
    paginate_by = 3  # if pagination is desired

    def post(self, request):
        form = CartProductForm(request.POST)
        id_product = request.POST.get('product')
        cart_id_user = Cart.objects.get(UserId=self.request.user.id)
        check_product_in_cart = CartProducts.objects.filter(CartId=cart_id_user, ProductsId=id_product)

        if not check_product_in_cart:
            if form.is_valid():
                form.save()
                messages.info(request, 'dodano produkt')
        else:
            messages.info(request, 'produkt juz w koszyku')

        return super(SearchView, self).get(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_filter'] = ProductFilter(self.request.GET)
        if self.request.user.is_authenticated:
            cart_id, bool = Cart.objects.filter(UserId=self.request.user.id).get_or_create(
                        defaults={'UserId': self.request.user})
            context['form'] = CartProductForm(initial={'CartId': cart_id, 'ProductsId': self.kwargs.get('pk')})
            context['cart'] = cart_id
        return context


class Login(LoginView):
    template_name = 'Products/Login.html'


# class Login(generic.TemplateView):
#     template_name = 'Products/Login.html'
#
#     def post(self, request):
#
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         user = authenticate(request, username=username, password=password)
#         print(request)
#         if user is not None:
#             login(request, user)
#             return redirect('Products:Main')
#         else:
#             return render(request, 'Products/Login.html',
#                           messages.info(request, 'błedne hasło lub login'))
#
#     def get_queryset(self):
#         return Category.objects.all()


class LogoutView(LogoutView):
    template_name = 'Products/Main.html'


class RegisterView (generic.TemplateView):
    template_name = 'Products/Register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CreateUserForm
        return context

    def post(self,request):
        form = CreateUserForm(request.POST)

        check_email=User.objects.filter(email=form.data['email'])
        if not check_email:
            if form.is_valid():
                form.save()
                messages.info(request, 'Zarejestrowano uzytkownika')
                user = User.objects.get(email=form.data['email'])

                adress = request.POST.get('email')
                file = render_to_string('Products/email_message/activate_email.html', {
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': generate_token.make_token(user),
                    'domain': get_current_site(request),
                    'user': user
                })
                send_email("Witaj "+user.username, adress, file, request)
                return redirect('Products:register_done')

        context = {'form': form}
        return render(request, 'Products/Register.html', context)


class VerificationView(generic.TemplateView):

    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            print('ers')
            user = User.objects.get(pk=uid)
        except Exception as identifier:
            user = None
        if user is not None and generate_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Konto zostało aktywowane')
            return redirect('Products:Login')
        return redirect('Products:Main')


class RegisterDone (generic.TemplateView):
    template_name = 'Products/Register_acount.html'


class CartView(ListView):
    template_name = 'Products/Cart.html'

    def post(self, request):
        if 'delete' in request.POST:
            cart_id = request.POST.get('delete')
            item = CartProducts.objects.get(id=cart_id)
            item.delete()
        if 'countChange' in request.POST:
            item = CartProducts.objects.get(id=request.POST.get('product'))
            form = CartProductChangeCountForm(request.POST or None, instance=item)
            if form.is_valid():
                form.save()
        if 'send' in request.POST:
            cart_id = Cart.objects.get(UserId = request.user.id)
            context = {'product': Products.objects.all()}
            context['cart'] = CartProducts.objects.filter(CartId=cart_id)
            file = render_to_string('Products/email_message/cart_email.html', context, request)
            adress = request.POST.get('mail')
            send_email("Twój koszyk", adress,file, request)
        return redirect('Products:Cart')

    def get_queryset(self):
        return Category.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id, bool = Cart.objects.filter(UserId=self.request.user.id)\
            .get_or_create(defaults={'UserId': self.request.user})
        context['products_in_cart'] = CartProducts.objects.filter(CartId=cart_id)

Products/templates/Products/Cart.html
{% extends 'Products/Main.html' %}
{% block cart %}
{% load static %}
{% load widget_tweaks %}



{% for message in messages %}
            <p id="messages">{{message}}</p>
        {% endfor %}
{% if products_in_cart %}
    <form method="post" name="send" action="">
        {% csrf_token %}
        <input type="submit" name=send value="wyslij swój koszyk na email ">
        <input type="email" name="mail" placeholder="wpisz email" value={{request.user.email}}>

    </form>


    {% for i in products_in_cart %}
        <div style="width:800px; float:left ">
            <div style="width:500px; float:left ">
                <div style="width:400px; float:left ">
                    <a href="{% url 'Products:Product' i.ProductsId.id %}">{{i.ProductsId}}</a></p>
                Cena: {{i.ProductsId.price }}

                </div>

                <div style="width:100px; float:right ">
                    <div style=" float:left "><img src=" {{i.ProductsId.image.url}}" alt="cos niedziała XD" width="50px"></p></div>

                </div>

            </div>

            <div style="width:200px; float:left ">


                 <form method="post" name="countChange" action="">
                     {% csrf_token %}
                   Ilosc: {% render_field formChange.Count  value=i.Count  step=1   min=1   max=100 %}
                     {% render_field formChange.product value=i.id hidden=True %}
                     <input type="submit" value="przelicz" name="countChange" >
                     </p>
                     łączna kwota: {{i.SumPrice}}

                </form>

                 <form method="post" name="del" action="">
                    {% csrf_token %}
                     <input type="submit" value="usuń ">
                     <input type="text" name="delete" value={{i.id}} hidden=True>
                </form>
            </div>


        </div>
        <hr>

    {% endfor %}


    Suma całego koszyka {{products_in_cart.0.SumPriceAll}}


{% else %}
    brak produktów w koszyku przejdz do produktu i dodaj go ;D
{% endif %}
{% endblock %}

Products/templates/Products/Categories.html
    {% for category in category_list %}
            <a href="{% url 'Products:Category' category.id  %}?page=1">{{ category.name }}</a></p>

        {% endfor %}

Products/templates/Products/Category.html
{% extends 'Products/Main.html' %}
{% block category %}
{% load static %}
{% load widget_tweaks %}
{% load product_extras %}


{% if '/category/' in request.get_full_path %}
    <h1>Kategoria: {{cat}}</h1>

{% else %}
    <h1>Szukaj:  {{request.GET.title__icontains}}</h1>

{% endif %}

{% for message in messages %}
    <p id="messages">{{message}}</p>
{% endfor %}

<a href="{% my_url 'asc' 'ordering'  request.GET.urlencode %}"> Cena /\</a>
<a href="{% my_url 'dsc' 'ordering'  request.GET.urlencode %}"> Cena \/</a></p>



 {% for product in object_list %}


            <div style="width:500px; float:left "><a href="{% url 'Products:Product' product.id %}">{{ product.title }}</a>

                <div style="width:500px; float:left ">

                    <div style="width:100px; margin-top: 15px; float:left ">
                        {% if  request.user.is_authenticated%}
                        <form method="POST" action="">
                            {% csrf_token %}

                            {% render_field form.Count  value='1' hidden=True   %}
                            {% render_field form.cart   value=cart hidden=True %}
                             {% render_field form.product value=product.id hidden=True %}

                            <input class="btn login_btn" type="submit" value="dodaj do koszyka ">

                     </form>
                        {% endif %}
                    </div>
                </div>
            </div>
             <div style="width:200px; float:left ">
                        </p>Cena: {{ product.price }}
             </div>
            <div style="width:100px; float:right "><img src=" {{product.image.url}}" alt="cos niedziała XD" height="100px"></p></div>
            <div style="clear:both"></div>

        {% endfor %}
 {% if page_obj.has_previous %}
            <a href="{% my_url 1 'page'  request.GET.urlencode %}"> 1</a>
            <a href="{% my_url page_obj.previous_page_number 'page'  request.GET.urlencode %}">< Strona</a>
        {% endif %}
{% if page_obj.has_next %}
            <a href="{% my_url page_obj.next_page_number 'page'  request.GET.urlencode %}"> Strona ></a>
            <a href="{% my_url page_obj.paginator.num_pages 'page'  request.GET.urlencode %}">{{product_pagination.paginator.num_pages}}</a>
        {% endif %}

{% endblock %}

Products/templates/Products/Login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">Logowanie</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Email / Login" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				 {% for message in messages %}
    			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
   				 {% endfor %}
				{% if form.errors %}
				<p>Błędne hasło lub login</p>
				{% endif %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Nie masz konta? <a href="{% url 'Products:Register' %}" class="ml-2">Rejestracja</a>

					</div>
					<div class="d-flex justify-content-center links">
						<a href="{% url 'Products:reset_password' %}" class="ml-2">Nie pamiętam hasła</a>

					</div>

			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

Products/templates/Products/Main.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Products/style.css' %}">

<div>
    <h1>{% include 'Products/Navbar.html' %}</h1>
</div>

<div style="clear:both"></div>


<div style="width:200px; float:left">

    {% include 'Products/Categories.html' %}
</div>

<div style="width:800px; float:left">
    {% block product %}
    {% block user %}
    {% block search %}
    {% block cart %}
    {% block category %}
    {% block prs %}
    {% block prs1 %}
    {% block prs2 %}
    {% block prs3 %}

        Super fajny sklep musisz cos kupic
        <img src="{% static 'Images/cart.png' %}" alt="cos niedziała XD" width="200" height="200">

    {% endblock %}
    {% endblock %}
    {% endblock %}
    {% endblock %}
    {% endblock %}
    {% endblock %}
    {% endblock %}
    {% endblock %}
    {% endblock %}

</div>


<div style="clear:both"></div>

Products/templates/Products/Navbar.html
{% load static %}
<div style="width:700px; display:inline ">
<a href="{% url 'Products:Main' %}"><img src="{% static 'Images/home-icon.png' %}" alt="cos niedziała XD" width="40" height="40"></a>

  <div style="width:300px; display:inline ">
  <form method="GET" style="width:300px; display:inline" action="/search/">
    {% if '/search/' in request.get_full_path %}
    {{product_filter.form.title__icontains}}
    {% else %}
    <input  name="title__icontains" type="text" placeholder="szukaj np. intel">
    {% endif %}

    <input  type="submit" value="Szukaj ">

  </form>
  </div>

{% if  request.user.is_authenticated%}




{% if request.get_full_path != '/cart/' %}
  <a href="{% url 'Products:Cart' %}">Twoj koszyk</a>

{% endif %}
  <a href="{% url 'Products:User' %}">{{request.user}}</a>
  <a href="{% url 'Products:Logout' %}">wyloguj</a>

{% else %}

  <a href="{% url 'Products:Login' %}">zaloguj</a>
{% endif %}
</div>

Products/templates/Products/Password_reset.html
{% extends 'Products/Main.html' %}
{% block prs3 %}


<h3> Resetowanie hasła</h3>

<form method="post">
    {% csrf_token %}
    {{form}}
     <input type="submit" value="wyślij email">
</form>
{% endblock %}

Products/templates/Products/Password_reset_done.html
{% extends 'Products/Main.html' %}
{% block prs1 %}


<h3> Resetowanie hasła</h3>

<form method="post">
    Twoje hasło zostało zresetowane <a href="{% url 'Products:Login' %}">Zaloguj</a>

</form>
{% endblock %}

Products/templates/Products/Password_reset_form.html
{% extends 'Products/Main.html' %}
{% block prs2 %}
<h3> Resetowanie hasła</h3>

<form method="post">
    {% csrf_token %}
    {{form}}
     <input type="submit" value="Zmień hasło">
</form>
{% endblock %}

Products/templates/Products/Password_reset_sent.html
{% extends 'Products/Main.html' %}
{% block prs %}

<h3> Hasło zostało zresetowa</h3>
dalsze kroki zostaną wysłane na Twój Email

</form>
{% endblock %}

Products/templates/Products/Register_acount.html
{% extends 'Products/Main.html' %}
{% block prs %}

<h3> Konto zostało utworzone </h3>
Aby aktywować konto przejdz na swoją skrzynkę pocztową

    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}

{% endblock %}

Products/templates/Products/User-password.html
{% extends 'Products/Main.html' %}
{% block user %}

<h1>Zmiana hasła</h1>


    <form method="POST" action="">
           {% csrf_token %}

         {{form.as_p}}


           <input class="btn login_btn" type="submit" value="zmień hasło">


        </form>

{% endblock %}

Products/templates/Products/User.html
{% extends 'Products/Main.html' %}
{% block user %}

<h1>Witaj {{user.username}}</h1>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    Email: {{user.email}}
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="zapisz">

        </form>

         Aby zmienic hasło przejdz <a href="{% url 'Products:User-password' %}">Tutaj</a>
{% endblock %}